### ISSUE TITLE
There is no documentation about how to integrate into wordpress

### ISSUE THREAD

**Issue by cabfever** [jaredkotoff/phantombot-webpage-scripts#4]
Json files are filled with content in the output folder, but it seems the wordpress.php file is not displaying anything by default.

How do I have to integrate the code into my wordpress pages or even better: standalone php pages?

![grafik](https://user-images.githubusercontent.com/6763019/30166322-3c1e7e76-93e3-11e7-8ea9-f8d88d34ecc0.png)

**Comment by cabfever** [comment]
This is how the json file looks like: 

![grafik](https://user-images.githubusercontent.com/6763019/30166765-98bc65f2-93e4-11e7-83af-66073b0205e5.png)

So there is definatly content inside the json files which means, the api connection to my phantombot is working.

**Comment by jaredcat** [comment]
Yea need to update the readme.  
Its basically copy and paste the `wordpress.php` files into your WordPress page template. I have mine directly under the `content` load block.
Make sure you update the ` $filename` variable with the correct path to the json output folder.
